# Generated by Django 4.0.4 on 2022-05-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malumot',
            old_name='nomi',
            new_name='first_name',
        ),
    ]
